In [81]:
# 1 create and display a one-dimensional array-like object containing an array of data using Pandas module.
import pandas as pd
import numpy as np
arr=[1,2,3,4,5]

series=pd.Series(arr)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [82]:
# 2 to convert a Panda module Series to Python list and it's type.

print(series)
print("Series to List")
arr=series.to_list()
print(arr)
print(type(arr))

0    1
1    2
2    3
3    4
4    5
dtype: int64
Series to List
[1, 2, 3, 4, 5]
<class 'list'>


In [121]:
#3.to add, subtract, multiple and divide two Pandas Series.

series1 = pd.Series([2, 4, 6, 8, 10])
series2 = pd.Series( [1, 3, 5, 7, 9])
print("Addition")
print(series1 + series2)
print("\nSubtraction")
print(series1-series2)
print("\nMultiplication")
print(series1 * series2)
print("\nDivision")
print(series1/series2)


Addition
0     3
1     7
2    11
3    15
4    19
dtype: int64

Subtraction
0    1
1    1
2    1
3    1
4    1
dtype: int64

Multiplication
0     2
1    12
2    30
3    56
4    90
dtype: int64

Division
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [84]:
 # 4 to get the powers of an array values element-wise.
a=pd.Series([0,1,2,3,4,5,6])
b=pd.Series([3,3,3,3,3,3,3])

print("Original Array")
print(a.values)
print(b.values)

print("First array elements raised to powers from second array, element-wise:")
print((a**b).values)

Original Array
[0 1 2 3 4 5 6]
[3 3 3 3 3 3 3]
First array elements raised to powers from second array, element-wise:
[  0   1   8  27  64 125 216]


In [85]:
#5.create and display a DataFrame from a specified dictionarydata which has the index labels.
exam_data = {'name': ['Anastasia','Dima','Katherine','James','Emily','Michael','Matthew','Laura','Kevin','Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes','no','yes','no','no','yes','yes','no','no','yes']}


labels=['a','b','c','d','e','f','g','h','i','j']

df=pd.DataFrame(exam_data,labels)
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [86]:
#6 to display a summary of the basic information about a specified Data Frame and its data.

print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10 non-null     object 
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64  
 3   qualify   10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes
None
           score   attempts
count   8.000000  10.000000
mean   13.562500   1.900000
std     4.693746   0.875595
min     8.000000   1.000000
25%     9.000000   1.000000
50%    13.500000   2.000000
75%    17.125000   2.750000
max    20.000000   3.000000


In [87]:
#8.to select the 'name' and 'score' columns from the following DataFrame.


print(df["name"])
print()
print(df["score"])

a    Anastasia
b         Dima
c    Katherine
d        James
e        Emily
f      Michael
g      Matthew
h        Laura
i        Kevin
j        Jonas
Name: name, dtype: object

a    12.5
b     9.0
c    16.5
d     NaN
e     9.0
f    20.0
g    14.5
h     NaN
i     8.0
j    19.0
Name: score, dtype: float64


In [88]:
# 9 to select the specified columns and rows from a given data frame.

print(df.loc[('a','c','e','f'),["name","score"]])

        name  score
a  Anastasia   12.5
c  Katherine   16.5
e      Emily    9.0
f    Michael   20.0


In [89]:
# 10 to select the rows where the number of attempts in the examination is greater than 2.

df2=df["attempts"]>2
print(df[df2])

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


In [90]:
# 11 to count the number of rows and columns of a DataFrame.

print("Number of rows : ",end=" ")
rows,columns=df.shape
print(rows)
print(f"Number of columns : {columns}")


Number of rows :  10
Number of columns : 4


In [91]:
# 12.to select the rows where the score is missing, i.e. is NaN.

print(df[df.isnull().any(axis=1)] )

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


In [92]:
#13. to select the rows where number of attempts in the examination is less than 2 and score greater than 15.

df2=(df["attempts"]< 2) & (df["score"]> 15)
print(df[df2])

    name  score  attempts qualify
j  Jonas   19.0         1     yes


In [93]:
#14.  to change the score in row 'd' to 11.5.

df.loc['d',"score"]=11.5
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [94]:
#15. to calculate the sum of the examination attempts by the students.

print(df["attempts"].sum())

19


In [120]:
#16 to calculate the mean score for each different student inDataFrame.

mean_value=df["score"].mean()
print(mean_value)

13.333333333333334


In [103]:
# 17. to append a new row 'k' to data frame with given values for each column.Now delete the new row and return the original DataFrame.

df.loc["k"]={"name":"Suresh", "score": 15.5, "attempts": 1, "qualify": "yes", "label": "k"}
print("Added a row k")
print(df)
print("\nDeleted the row k")
df=df.drop("k")
print(df)

Added a row k
        name  score qualify  attempts
a  Anastasia   12.5    True         1
b       Dima    9.0   False         3
c  Katherine   16.5    True         2
d      James   11.5   False         3
e      Emily    9.0   False         2
f    Michael   20.0    True         3
g    Matthew   14.5    True         1
h      Laura    NaN   False         1
i      Kevin    8.0   False         2
j      Jonas   19.0    True         1
k     Suresh   15.5     yes         1

Deleted the row k
        name  score qualify  attempts
a  Anastasia   12.5    True         1
b       Dima    9.0   False         3
c  Katherine   16.5    True         2
d      James   11.5   False         3
e      Emily    9.0   False         2
f    Michael   20.0    True         3
g    Matthew   14.5    True         1
h      Laura    NaN   False         1
i      Kevin    8.0   False         2
j      Jonas   19.0    True         1


In [97]:
#18.to sort the DataFrame first by 'name' in descending order, then by 'score' in ascending order.

print("sort by name")
print(df.sort_values("name",ascending=False))

print("\nsort by score")
print(df.sort_values("score"))


sort by name
        name  score  attempts qualify
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes

sort by score
        name  score  attempts qualify
i      Kevin    8.0         2      no
b       Dima    9.0         3      no
e      Emily    9.0         2      no
d      James   11.5         3      no
a  Anastasia   12.5         1     yes
g    Matthew   14.5         1     yes
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
f    Michael   20.0         3     yes
h      Laura    NaN         1      no


In [98]:
# 19.to replace the 'qualify' column contains the values 'yes' and'no' with True and False.

df["qualify"]=df["qualify"].replace({"no":False,"yes":True})
print(df)

        name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James   11.5         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True


/var/folders/n2/0x8c6lh57hsdrlnsy74qzkvr0000gn/T/ipykernel_12311/2612953879.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["qualify"]=df["qualify"].replace({"no":False,"yes":True})


In [99]:
# 20.to delete the 'attempts' column from the DataFrame.

df=df.drop(columns="attempts")
print(df)

        name  score  qualify
a  Anastasia   12.5     True
b       Dima    9.0    False
c  Katherine   16.5     True
d      James   11.5    False
e      Emily    9.0    False
f    Michael   20.0     True
g    Matthew   14.5     True
h      Laura    NaN    False
i      Kevin    8.0    False
j      Jonas   19.0     True


In [104]:
# 21 . to insert a new column in existing DataFrame.

df["attempts"]=[1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
df

name  score qualify  attempts
a  Anastasia   12.5    True         1
b       Dima    9.0   False         3
c  Katherine   16.5    True         2
d      James   11.5   False         3
e      Emily    9.0   False         2
f    Michael   20.0    True         3
g    Matthew   14.5    True         1
h      Laura    NaN   False         1
i      Kevin    8.0   False         2
j      Jonas   19.0    True         1

In [ ]:
#22.to iterate over rows in a DataFrame.

for index,row in df.iterrows():
    print(f"Index: {index}, Name: {row['name']}, Score: {row['score']},Attempts: {row['attempts']}")



Index: a, Name: Anastasia, Score: 12.5,Attempts: 1
Index: b, Name: Dima, Score: 9.0,Attempts: 3
Index: c, Name: Katherine, Score: 16.5,Attempts: 2
Index: d, Name: James, Score: 11.5,Attempts: 3
Index: e, Name: Emily, Score: 9.0,Attempts: 2
Index: f, Name: Michael, Score: 20.0,Attempts: 3
Index: g, Name: Matthew, Score: 14.5,Attempts: 1
Index: h, Name: Laura, Score: nan,Attempts: 1
Index: i, Name: Kevin, Score: 8.0,Attempts: 2
Index: j, Name: Jonas, Score: 19.0,Attempts: 1


In [119]:
#23 to get list from DataFrame column headers.

print(list(df.columns))

['name', 'score', 'qualify', 'attempts']
